In [1]:
#Install Pandas
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#impoet pandas
import pandas as pd

In [3]:
#Create a list of data
data = [1,2,3,4,5,10]

In [4]:
data

[1, 2, 3, 4, 5, 10]

In [5]:
type(data)

list

In [7]:
# Create Series from a list
s=pd.Series(data)
s

0     1
1     2
2     3
3     4
4     5
5    10
dtype: int64

In [8]:
type(s)

pandas.core.series.Series

In [10]:
# Create a DataFrame from the Series
df = pd.DataFrame(s,columns =['num'])
df

   num
0    1
1    2
2    3
3    4
4    5
5   10